pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        valid_languages:
            - de
            - en
        fallback_languages:
            de: ''
            en: de
        required_languages:
            - de
        default_language: de
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: 5
        error_pages:
            default: /error
            localized:
                de: ''
    objects:
        versions:
            days: null
            steps: 5
    assets:
        versions:
            days: null
            steps: 5
    email:
        debug:
            email_addresses: your@debugmail.com
