pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    blogpost-gallery-thumbnail:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 100
                                    forceResize: true
                        medias: {  }
                        name: blogpost-gallery-thumbnail
                        description: ''
                        group: Blogpost
                        format: JPEG
                        quality: 65
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1748701301
                        creationDate: 1748701251
                        preserveAnimation: false
