pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    eventList:
                        items:
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 360
                                    forceResize: false
                        medias: {  }
                        name: eventList
                        description: ''
                        group: Events
                        format: JPEG
                        quality: 60
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1727811222
                        creationDate: 1727811172
                        preserveAnimation: false
