pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    eventStart:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 450
                                    height: 338
                                    forceResize: false
                        medias: {  }
                        name: eventStart
                        description: ''
                        group: Events
                        format: JPEG
                        quality: 65
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1729954900
                        creationDate: 1729954761
                        preserveAnimation: false
