pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    eventDetailsGallery:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 1600
                                    height: 1200
                                    forceResize: false
                        medias: {  }
                        name: eventDetailsGallery
                        description: ''
                        group: Events
                        format: JPEG
                        quality: 70
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1729324036
                        creationDate: 1729017315
                        preserveAnimation: false
