pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    rentalObjectDetailsGalleryThumbnail:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 138
                                    forceResize: false
                        medias: {  }
                        name: rentalObjectDetailsGalleryThumbnail
                        description: ''
                        group: Rental
                        format: JPEG
                        quality: 60
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1729324219
                        creationDate: 1728327905
                        preserveAnimation: false
