pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    startSlider:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 1900
                                    height: 650
                                    forceResize: true
                        medias: {  }
                        name: startSlider
                        description: ''
                        group: Start
                        format: JPEG
                        quality: 70
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1730059559
                        creationDate: 1730059293
                        preserveAnimation: false
