pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    teaser1600:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 1600
                                    height: 415
                                    positioning: topcenter
                                    forceResize: false
                        medias: {  }
                        name: teaser1600
                        description: ''
                        group: ''
                        format: JPEG
                        quality: 65
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1728412364
                        creationDate: 1728375330
                        preserveAnimation: false
