pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    teaser1900x900:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 1900
                                    height: 900
                                    positioning: topcenter
                                    forceResize: false
                        medias: {  }
                        name: teaser1900x900
                        description: ''
                        group: ''
                        format: JPEG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1728586560
                        creationDate: 1728586523
                        preserveAnimation: false
