pimcore:
    documents:
        doc_types:
            definitions:
                8ac6a960-37a9-4e14-92bd-cead22a574c9:
                    name: 1-spaltig
                    group: CMS
                    controller: 'App\Controller\DefaultController::cmsOneColumnAction'
                    template: null
                    type: page
                    priority: 0
                    creationDate: 1729874720
                    modificationDate: 1729874749
                    staticGeneratorEnabled: false
