pimcore:
    assets:
        metadata:
            predefined:
                definitions:
                    2d483601-bd60-4a06-8eec-97062b347226:
                        name: redaxoArticleSliceId
                        description: null
                        type: input
                        targetSubtype: null
                        data: null
                        config: null
                        language: null
                        group: null
                        creationDate: 1727111666
                        modificationDate: 1727111680
