pimcore:
    assets:
        metadata:
            predefined:
                definitions:
                    e400ead3-0f55-429e-8fbc-6b215134a1a2:
                        name: redaxoId
                        description: ''
                        type: input
                        targetSubtype: null
                        data: ''
                        config: ''
                        language: null
                        group: ''
                        creationDate: 1727027466
                        modificationDate: 1727027511
